export * from "./Building.icon";
export * from "./Camera.icon";
export * from "./Chat.icon";
export * from "./Clock.icon";
export * from "./Cross.icon";
export * from "./Edit.icon";
export * from "./GreenTick.icon";
export * from "./Info.icon";
export * from "./Memory.icon";
export * from "./Pencil.icon";
export * from "./Pod.icon";
export * from "./Time.icon";
export * from "./User.icon";
export * from "./UserInfo.icon";
export * from "./UserPrimary.icon";
export * from "./GreenVerify.icon"
